"""Structured session handoff — evidence for the next run (not chat-only memory)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from meris.harness.paths import harness_root
from meris.harness.sessions import SessionRecord


def handoff_path(workspace: Path) -> Path:
    return harness_root(workspace) / "handoff.md"


def _last_assistant_snippet(record: SessionRecord, *, max_len: int = 400) -> str:
    for msg in reversed(record.messages):
        if msg.get("role") == "assistant" and msg.get("content"):
            text = str(msg["content"]).strip()
            return text[:max_len] + ("…" if len(text) > max_len else "")
    return "(none)"


def _tool_summary(record: SessionRecord) -> str:
    names: list[str] = []
    for msg in record.messages:
        if msg.get("role") == "assistant":
            for tc in msg.get("tool_calls") or []:
                fn = tc.get("function") or {}
                name = fn.get("name", "")
                if name and name not in names:
                    names.append(name)
    return ", ".join(names[:12]) if names else "(none)"


def write_session_handoff(
    workspace: Path,
    record: SessionRecord,
    *,
    status: str,
    verifier_output: str = "",
) -> Path | None:
    """Write `.meris/handoff.md` with saw/did/verified/risks for failed or exhausted runs."""
    if status not in ("dod_failed", "error", "max_turns", "cancelled"):
        return None

    ws = workspace.resolve()
    path = handoff_path(ws)
    path.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    verified = "PASS" if status == "completed" else "FAIL or incomplete"
    if verifier_output.strip():
        verified = verifier_output.strip()[:1200]

    body = f"""# Session handoff (auto)

Updated: {ts}

## Context

- **Session**: `{record.id}`
- **Mode**: {record.mode}
- **Status**: {status}
- **Task**: {record.task[:500]}

## 看到了什么

- Turn {record.turn}/{record.max_turns}
- Tools used: {_tool_summary(record)}
- Last assistant: {_last_assistant_snippet(record)}

## 做了什么

- See session file: `.meris/sessions/{record.id}.json`

## 验证了什么

```
{verified}
```

## 剩余风险 / 下一轮接点

- Do not assume this task completed — check verifier output above.
- Run `meris ratchet scan` if this failure repeats.
- Read `PROGRESS.md` Ratchet summary before continuing.

---
*Generated by Meris handoff — replace on next failed/exhausted run.*
"""
    path.write_text(body, encoding="utf-8")
    return path


def load_handoff_for_prompt(workspace: Path, *, max_chars: int = 2400) -> str:
    """Compact handoff for system prompt (prior failed/exhausted session)."""
    path = handoff_path(workspace.resolve())
    if not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return ""
    # Skip boilerplate footer
    if "---" in text:
        text = text.split("---")[0].strip()
    return text[:max_chars]
